name: elpako
description: Elpako is an API wrapper for the Elpako Digital Signatures API.
version: 0.0.1
repository: https://github.com/Shalomka/elpako

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.2.1
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^4.0.0
